// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBiCqN5n_h-0sq208GrM5zGNDPhKb6iuaI',
    appId: '1:114231577032:web:fc98b630b47c261aac58fd',
    messagingSenderId: '114231577032',
    projectId: 'car-rental-flutter-268bd',
    authDomain: 'car-rental-flutter-268bd.firebaseapp.com',
    storageBucket: 'car-rental-flutter-268bd.appspot.com',
    measurementId: 'G-G7YEJT30M4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJoP3mqyomPcMzNIGUWApUYy7luTD-chI',
    appId: '1:114231577032:android:e5f0f9f00537bf32ac58fd',
    messagingSenderId: '114231577032',
    projectId: 'car-rental-flutter-268bd',
    storageBucket: 'car-rental-flutter-268bd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBRb1YIPqHCfyAVHWFFjint1pbXLM0Oe8c',
    appId: '1:114231577032:ios:accbe2d404729856ac58fd',
    messagingSenderId: '114231577032',
    projectId: 'car-rental-flutter-268bd',
    storageBucket: 'car-rental-flutter-268bd.appspot.com',
    iosBundleId: 'com.example.carRentalFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBRb1YIPqHCfyAVHWFFjint1pbXLM0Oe8c',
    appId: '1:114231577032:ios:accbe2d404729856ac58fd',
    messagingSenderId: '114231577032',
    projectId: 'car-rental-flutter-268bd',
    storageBucket: 'car-rental-flutter-268bd.appspot.com',
    iosBundleId: 'com.example.carRentalFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBiCqN5n_h-0sq208GrM5zGNDPhKb6iuaI',
    appId: '1:114231577032:web:01a878a27ea10d24ac58fd',
    messagingSenderId: '114231577032',
    projectId: 'car-rental-flutter-268bd',
    authDomain: 'car-rental-flutter-268bd.firebaseapp.com',
    storageBucket: 'car-rental-flutter-268bd.appspot.com',
    measurementId: 'G-E37L57110N',
  );

}